-- CreateEnum
CREATE TYPE "CustomerStatus" AS ENUM ('CONTRACT_SENT', 'PENDING_PAYMENT_AGREEMENT', 'PENDING_DOCS', 'DISPUTE_1', 'DISPUTE_2', 'DISPUTE_3', 'ACTIVE_ALERT', 'PENDING_LOYALTY', 'LOYALTY_OK', 'CANCELLED');

-- AlterTable
ALTER TABLE "Lead" ADD COLUMN     "customerStatus" "CustomerStatus";
